name: battery-state-estimation
channels:
  - conda-forge/label/cf202003
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _tflow_select=2.3.0
  - abseil-cpp=20210324.2
  - absl-py=0.15.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - astor=0.8.1
  - asttokens=2.0.5
  - astunparse=1.6.3
  - async-timeout=4.0.1
  - attrs=21.4.0
  - babel=2.9.1
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.4
  - bottleneck=1.3.4
  - brotli=1.0.9
  - brotlipy=0.7.0
  - c-ares=1.18.1
  - ca-certificates=2022.4.26
  - cachetools=4.2.2
  - certifi=2022.6.15
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cryptography=3.4.8
  - cycler=0.11.0
  - dataclasses=0.8
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.4.4
  - flatbuffers=2.0.0
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - frozenlist=1.2.0
  - gast=0.4.0
  - giflib=5.2.1
  - glib=2.69.1
  - google-auth=2.6.0
  - google-auth-oauthlib=0.4.1
  - google-pasta=0.2.0
  - grpcio=1.42.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.10.0
  - hdf5=1.10.6
  - icu=58.2
  - idna=3.3
  - importlib-metadata=4.11.3
  - intel-openmp=2021.4.0
  - ipykernel=6.9.1
  - ipython=8.3.0
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jinja2=3.0.3
  - jpeg=9e
  - json5=0.9.6
  - jsonschema=4.4.0
  - jupyter_client=7.2.2
  - jupyter_core=4.10.0
  - jupyter_server=1.17.1
  - jupyterlab=3.3.2
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.12.0
  - keras=2.4.3
  - keras-preprocessing=1.1.2
  - kiwisolver=1.4.2
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - libcurl=7.82.0
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=11.2.0
  - libnghttp2=1.46.0
  - libopenblas=0.3.18
  - libpng=1.6.37
  - libprotobuf=3.14.0
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libuv=1.42.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.15
  - libxml2=2.9.14
  - lz4-c=1.9.3
  - markdown=3.3.4
  - markupsafe=2.1.1
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - multidict=5.2.0
  - munkres=1.1.4
  - nbclassic=0.3.5
  - nbclient=0.5.13
  - nbconvert=6.4.4
  - nbformat=5.3.0
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - nodejs=12.4.0
  - notebook=6.4.11
  - numexpr=2.8.1
  - numpy-base=1.19.2
  - oauthlib=3.2.0
  - openssl=1.1.1o
  - opt_einsum=3.3.0
  - packaging=21.3
  - pandas=1.4.2
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.0.1
  - pip=21.2.4
  - plotly=5.6.0
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.20
  - protobuf=3.14.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pygments=2.11.2
  - pyjwt=2.1.0
  - pyopenssl=21.0.0
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.12
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.15.1
  - python-flatbuffers=1.12
  - python_abi=3.9
  - pytz=2022.1
  - pyyaml=6.0
  - pyzmq=22.3.0
  - qt=5.9.7
  - readline=8.1.2
  - requests=2.27.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scipy=1.7.3
  - send2trash=1.8.0
  - setuptools=61.2.0
  - sip=4.19.13
  - six=1.16.0
  - snappy=1.1.9
  - sniffio=1.2.0
  - soupsieve=2.3.1
  - sqlite=3.38.3
  - stack_data=0.2.0
  - tenacity=8.0.1
  - tensorboard=2.6.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.6.0
  - tensorflow=2.4.1
  - tensorflow-base=2.4.1
  - tensorflow-estimator=2.6.0
  - termcolor=1.1.0
  - terminado=0.13.1
  - testpath=0.6.0
  - tk=8.6.12
  - tornado=6.1
  - traitlets=5.1.1
  - typing-extensions=4.1.1
  - typing_extensions=4.1.1
  - tzdata=2022a
  - urllib3=1.26.9
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - werkzeug=2.0.3
  - wheel=0.35.1
  - wrapt=1.13.3
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zeromq=4.3.4
  - zipp=3.8.0
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - joblib==1.1.0
    - scikit-learn==1.1.1
    - threadpoolctl==3.1.0
    - tikzplotlib==0.10.1
    - webcolors==1.12
